defaults: &defaults
  working_directory: ~/repo
version: 2

references:
  install_serverless: &install_serverless
    run:
      name: Install Serverless and AWS CLI
      command: |
        sudo npm i -g serverless
        npm install
        sudo apt-get install awscli --upgrade
  serverless_deploy: &serverless_deploy
    run:
      name: Deploy application
      command: |
        sls deploy --stage $STAGE
  
jobs:
  deploy_dev:
    <<: *defaults
    docker:
      - image: circleci/node:8.10
    environment:
      STAGE: dev
    steps:
      - checkout
      - *install_serverless
      - *serverless_deploy
  deploy_prod:
    <<: *defaults
    docker:
      - image: circleci/node:8.10
    environment:
      STAGE: prd
    steps:
      - checkout
      - *install_serverless
      - *serverless_deploy
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
      - confirm_deploy:
          type: approval
          requires:
            - deploy_dev
      - deploy_prod:
          requires:
            - confirm_deploy
