defaults: &defaults
  working_directory: ~/repo
version: 2

references:
  install_serverless: &install_serverless
    run:
      name: Install Serverless
      command: |
        sudo npm i -g serverless
        npm install
  install_aws_cli: &install_aws_cli
    run:
      name: Install AWS CLI
      command: |
        sudo apt-get install awscli --upgrade
  
jobs:
  deploy_dev:
    <<: *defaults
    docker:
      - image: circleci/node:8.10
    environment:
      STAGE: dev
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - *install_serverless
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - *install_aws_cli
      - run:
        name: Deploy application
        command: |
          sls deploy --stage dev
  deploy_prod:
    <<: *defaults
    docker:
      - image: circleci/node:8.10
    environment:
      STAGE: prd
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - *install_serverless
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - *install_aws_cli
      - run:
          name: Deploy application
          command: |
            sls deploy --stage prd
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
      - confirm_deploy:
          type: approval
          requires:
            - deploy_dev
      - deploy_prod:
          requires:
            - confirm_deploy
